In [30]:
import numpy as np 
import pandas as pd 
from sklearn.metrics import confusion_matrix 
from sklearn.model_selection import train_test_split 
from sklearn.tree import DecisionTreeClassifier 
from sklearn.metrics import accuracy_score 
from sklearn.metrics import classification_report 

In [33]:
# Load the dataset from URL and specify column names
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/balance-scale/balance-scale.data"
names = ['label', 'left_weight', 'left_dist', 'right_weight', 'right_dist']
dataset = pd.read_csv(url, names=names)


# Split the data into input variables (X) and target (y)
X = dataset.iloc[:,1:]
y = dataset.iloc[:,0]

# Split the data into training and test sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=60)


# Create a decision tree classifier object with specified parameters
clf = DecisionTreeClassifier(criterion="gini", random_state=100, max_depth=3, min_samples_leaf=5)

# Fit the decision tree classifier to the training data
clf.fit(X_train, y_train)

# Use the decision tree classifier to make predictions on the test data
y_pred = clf.predict(X_test)

# Calculate and print confusion matrix, accuracy score, and classification report
print("Confusion Matrix:")
print(confusion_matrix(y_test, y_pred))

print("\nAccuracy Score:", accuracy_score(y_test, y_pred))

print("\nClassification Report:")
print(classification_report(y_test, y_pred, zero_division=0))


Confusion Matrix:
[[ 0  5  8]
 [ 0 78 25]
 [ 0  7 65]]

Accuracy Score: 0.7606382978723404

Classification Report:
              precision    recall  f1-score   support

           B       0.00      0.00      0.00        13
           L       0.87      0.76      0.81       103
           R       0.66      0.90      0.76        72

    accuracy                           0.76       188
   macro avg       0.51      0.55      0.52       188
weighted avg       0.73      0.76      0.74       188

